substitutions:
  name: "m5-dial"
  
esphome:
  name: ${name}
  name_add_mac_suffix: false
  project:
    name: smarthomeyourself.m5_dial
    version: "1.1"
      
  platformio_options:
    lib_deps:
      - Wire
      - EEPROM
      - ArduinoJson
      - m5stack/M5Unified@0.1.14
      - m5stack/M5Dial@1.0.2

external_components:
  - source: github:szymonbultrowicz/m5-dial-for-esphome@szymonbultrowicz-patch-1
    components: [shys_m5_dial]

dashboard_import:
  package_import_url: github://SmartHome-yourself/szymonbultrowicz/shys-m5-dial.yaml@szymonbultrowicz-patch-1
  import_full_config: false

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: arduino
  flash_size: 8MB

logger:
  level: INFO
  logs:
    api: WARN
    esp32.preferences: WARN
    LOOP: WARN
    DISPLAY: WARN
    TOUCH: WARN
    HA_API: WARN
    DEVICE: WARN
    MEDIAPLAYER: WARN

api:
  homeassistant_states: true
  homeassistant_services: true
  custom_services: true
  
ota:
  platform: esphome
